"""
This module provides type definitions regarding pq-functions.
"""

# pylint: disable=no-name-in-module, too-few-public-methods, import-error

from dataclasses import dataclass
from typing import Dict

from data_provider.synthetic_data_generation.types.pq_tuple import PQTuple
from data_provider.synthetic_data_generation.modules.pq_functions.abstract_pq_function \
    import PQFunction


@dataclass
class GeneratedPQFunctions:
    """
    Class that contains all information about the pq-functions that were generated by a
    `PQFunctionGenerator`.
    """

    pq_functions: Dict[PQTuple, PQFunction]
    """Dictionary that contains the pq-function of the pq-tuple"""
